doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        use_savepoints: true
        types:
            email: App\Shared\Infrastructure\Doctrine\Type\EmailType
            phone_number: App\Shared\Infrastructure\Doctrine\Type\PhoneNumberType
            user_id: App\Shared\Infrastructure\Doctrine\Type\UserIdType
            notification_channel: App\NotificationPublisher\Infrastructure\Doctrine\Type\NotificationChannelType
            notification_status: App\NotificationPublisher\Infrastructure\Doctrine\Type\NotificationStatusType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Entity:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/NotificationPublisher/Domain/Entity'
                prefix: 'App\NotificationPublisher\Domain\Entity'
                alias: Entity
            ValueObject:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/NotificationPublisher/Domain/ValueObject'
                prefix: 'App\NotificationPublisher\Domain\ValueObject'
                alias: ValueObject

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
